security:
    role_hierarchy:
        ROLE_ADMIN: [ROLE_MANAGER,ROLE_USER]
    encoders:
        BugBundle\Entity\User:
            algorithm: bcrypt

    providers:
        my_db_provider:
            entity:
                class: BugBundle:User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false
        login:
            pattern:                        ^/(login|registration)$
            anonymous:                      true

        default:
            security: true
            anonymous: false
            pattern:    ^/
            http_basic: ~
            provider: my_db_provider
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path:   /logout
                target: /login

    access_control:
        - {path: ^/admin, role: ROLE_ADMIN}
