<?php

namespace BugBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * IssueCommentRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class IssueCommentRepository extends EntityRepository
{
}
